### ISSUE TITLE
UnicodeDecodeError with pip install maya on Windows 10

### ISSUE THREAD

**Issue by gbvanrenswoude** [timofurrer/maya#177]
Hi, raising this issue for awareness. Pip install on W10 raises an UnicodeDecodeError.
This seems to be a more general problem with pip on W10, but maya is hit.
```pip install maya```
```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 185: invalid continuation byte```

pip 19.1.1 / python 3.7

Ofcourse running the same on Linux works fine 😁

**Comment by gbvanrenswoude** [comment]
Workaround: 
```
    def get_metadata(self, name):
        if not self.egg_info:
            return ""
        value = self._get(self._fn(self.egg_info, name))
        return value.decode('mbcs') if six.PY3 else value # utf_8
```

pip/pip/_internal/__init__.py

**Comment by timofurrer** [comment]
As you already figured, that's not maya related. I'm going to close this. :tada:
